# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- id: "qrbill"
  main: "./cmd/qrbill-api"
  binary: "qrbill-api"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  - 386
- id: "qrbill-macos"
  main: "./cmd/qrbill-api"
  binary: "qrbill-api"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  goarch:
  - arm64
  - amd64
  hooks:
    post: "gon gon_{{ .Target }}.hcl"
archives:
- name_template: "qrbill_api_{{ .Os }}_{{ .Arch }}"
  builds:
  - qrbill
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: stapelberg
    name: qrbill
  extra_files:
    - glob: ./dist/qrbill_api_Darwin_*.dmg
